DROP DATABASE IF EXISTS DATABASE_NAME;
CREATE DATABASE IF NOT EXISTS DATABASE_NAME;
USE DATABASE_NAME;

DROP TABLE IF EXISTS alumnos_asistencia_participacion;
DROP TABLE IF EXISTS alumnos_evaluacion_oral;
DROP TABLE IF EXISTS evaluacion_oral;
DROP TABLE IF EXISTS asistencias_participaciones;
DROP TABLE IF EXISTS alumnos;
DROP TABLE IF EXISTS cohortes;
DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS roles;
